name: "Detect .csproj Name"
description: "Finds the first *.csproj in the working directory and outputs its base name."
author: "You"
branding:
  icon: search
  color: blue

outputs:
  csproj_name:
    description: "Base name of the first *.csproj found"
    value: ${{ steps.detect.outputs.csproj_name }}

runs:
  using: "composite"
  steps:
    - name: Get csproj name
      id: detect
      shell: pwsh
      run: |
        $item = Get-ChildItem -Filter *.csproj | Select-Object -First 1
        if (-not $item) { Write-Error "No .csproj found"; exit 1 }
        "csproj_name=$($item.BaseName)" >> $env:GITHUB_OUTPUT
