name: release alt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025
    steps:
    #   - name: Install gtksharp
    #     run: winget install -e --id Mono.gtksharp --disable-interactivity --accept-source-agreements
      - name: Remove msstore source
        run: winget source remove msstore
      - name: Install Mono
        run: winget install -e --id Mono.Mono --accept-package-agreements --accept-source-agreements --disable-interactivity
      - name: Find mono
        run: " \"C:\\Program Files\\Mono\\bin\\pdb2mdb.bat\" test"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Publish
        run: dotnet publish

      # # --- Zip the publish output ---
      # - name: Zip publish output
      #   shell: pwsh
      #   run: |
      #     if (Test-Path "${{ env.ZIP_NAME }}.zip") { Remove-Item -Force "${{ env.ZIP_NAME }}.zip" }
      #     Compress-Archive -Path "${{ env.PUBLISH_DIR }}\*" -DestinationPath "${{ env.ZIP_NAME }}.zip"

      # # --- Upload artifacts ---
      # - name: Upload zipped output
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ env.ZIP_NAME }}
      #     path: ${{ env.ZIP_NAME }}.zip
      #     if-no-files-found: error
