name: release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish
        run: dotnet publish --artifacts-path "C:\out"

      - name: Detect csproj
        id: csproj
        uses: ./.github/actions/detect-csproj

      - name: Get AssemblyName
        id: asm
        uses: ./.github/actions/get-assembly-name
        with:
          csproj: ${{ steps.csproj.outputs.csproj_name }}

      - name: Check dir
        run: |
          cd C:\out\publish\${{ steps.csproj.outputs.csproj_name }}\debug
          dir

      - name: Remove msstore source
        run: winget source remove msstore

      - name: Install Mono
        run: winget install -e --id Mono.Mono --accept-package-agreements --accept-source-agreements --disable-interactivity

      - name: PDB2MDB
        shell: cmd
        run: >
          "C:\Program Files\Mono\bin\pdb2mdb.bat"
          "C:\out\publish\${{ steps.csproj.outputs.csproj_name }}\debug\${{ steps.asm.outputs.assembly_name }}.dll"

      - name: Check dir
        run: |
          cd C:\out\publish\${{ steps.csproj.outputs.csproj_name }}\debug
          dir

      # # --- Zip the publish output ---
      # - name: Zip publish output
      #   shell: pwsh
      #   run: |
      #     if (Test-Path "${{ env.ZIP_NAME }}.zip") { Remove-Item -Force "${{ env.ZIP_NAME }}.zip" }
      #     Compress-Archive -Path "${{ env.PUBLISH_DIR }}\*" -DestinationPath "${{ env.ZIP_NAME }}.zip"

      # # --- Upload artifacts ---
      # - name: Upload zipped output
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ env.ZIP_NAME }}
      #     path: ${{ env.ZIP_NAME }}.zip
      #     if-no-files-found: error
