name: release alt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      UNITY_VERSION: 2021.3.10f1
    steps:
      - name: Pull UnityCI Editor Image
        run: docker pull unityci/editor:windows-2021.3.10f1-base-3.1.0
      - name: Run inside docker container
        run: |
          docker run --rm unityci/editor:windows-2021.3.10f1-base-3.1.0 \
            powershell -Command "Write-Output 'Hello from inside UnityCI container!'"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Publish
        run: dotnet publish

      # # --- Zip the publish output ---
      # - name: Zip publish output
      #   shell: pwsh
      #   run: |
      #     if (Test-Path "${{ env.ZIP_NAME }}.zip") { Remove-Item -Force "${{ env.ZIP_NAME }}.zip" }
      #     Compress-Archive -Path "${{ env.PUBLISH_DIR }}\*" -DestinationPath "${{ env.ZIP_NAME }}.zip"

      # # --- Upload artifacts ---
      # - name: Upload zipped output
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ env.ZIP_NAME }}
      #     path: ${{ env.ZIP_NAME }}.zip
      #     if-no-files-found: error
